"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.v1 = void 0;
const express_1 = require("express");
const userprofile_1 = require("./userprofile");
const mongo_rest_route_1 = require("../../../lib/mongo-rest-route");
const members_1 = require("../../../model/members");
const files_1 = require("../../../model/files");
const post_message_1 = require("./messages/post-message");
const upload_files_router_1 = require("./files/upload-files-router");
const check_user_1 = require("../check-user");
const users_1 = require("../../../model/users");
const messages_1 = require("../../../model/messages");
const router = (0, express_1.Router)();
exports.v1 = router;
const sortOrder = { order: 1 };
const sortNewest = { added: -1 };
router.get('/userprofile', userprofile_1.userprofile);
router.use('/files', (0, mongo_rest_route_1.MongoRestRouter)('files', files_1.fileSchema, { methods: ['GET'], sort: sortNewest }));
router.use('/members', (0, mongo_rest_route_1.MongoRestRouter)('members', members_1.memberSchema, { methods: ['GET'], sort: sortOrder }));
router.post('/messages', post_message_1.postMessage);
router.use('/users', (0, check_user_1.checkUser)('admin'), (0, mongo_rest_route_1.MongoRestRouter)('users', users_1.userSchema));
router.use('/members', (0, check_user_1.checkUser)('admin'), (0, mongo_rest_route_1.MongoRestRouter)('members', members_1.memberSchema, { methods: ['POST', 'PUT', 'PATCH', 'DELETE'] }));
router.use('/messages', (0, check_user_1.checkUser)('admin'), (0, mongo_rest_route_1.MongoRestRouter)('messages', messages_1.messageSchema, { methods: ['GET', 'DELETE'], sort: sortNewest }));
router.use('/files', (0, check_user_1.checkUser)('admin'), upload_files_router_1.uploadFilesRouter);
//# sourceMappingURL=index.js.map